name: CD

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**

jobs:
  cd:
    strategy:
      matrix:
        project:
          - name: Messages - ActiveMQ - Producer
            working-directory: ./services/active/producer
          - name: Messages - ActiveMQ - Consumer
            working-directory: ./services/active/consumer
          - name: Messages - Kafka - Producer
            working-directory: ./services/kafka/producer
          - name: Messages - Kafka - Consumer
            working-directory: ./services/kafka/consumer
          - name: Messages - RabbitMQ - Producer
            working-directory: ./services/rabbit/producer
          - name: Messages - RabbitMQ - Consumer
            working-directory: ./services/rabbit/consumer
          - name: Messages - Redis - Producer
            working-directory: ./services/redis/producer
          - name: Messages - Redis - Consumer
            working-directory: ./services/redis/consumer
    name: ${{ matrix.project.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: yarn install --network-timeout 86400000
        working-directory: ${{ matrix.project.working-directory }}
      - name: Unit Test
        run: yarn test
        working-directory: ${{ matrix.project.working-directory }}
      - name: Build Production
        run: yarn build
        working-directory: ${{ matrix.project.working-directory }}
